# Generated by Django 5.1.4 on 2025-01-12 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_items_barcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='staff_members',
        ),
        migrations.AddField(
            model_name='staff_member',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='Staff_members',
            field=models.ManyToManyField(to='api.staff_member'),
        ),
    ]
