# Generated by Django 5.1.4 on 2025-01-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
