# Generated by Django 5.1.4 on 2025-01-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='barcode',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
    ]
