# Generated by Django 5.1.4 on 2025-01-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_items_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='barcode',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
